package:
  name: openpmd_viewer
  version: "0.3.1"

source:
  git_rev: 0.3.1
  git_url: https://github.com/openPMD/openPMD-viewer.git

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - h5py
    - jupyter
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - h5py
    - jupyter

test:
  imports:
    - opmd_viewer

about:
  home: https://github.com/openPMD/openPMD-viewer
  license: BSD-3-clause
  license_file: LICENSE.txt